use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub enum BatchClass {
    Micro,
    Small,
    Medium,
    Institutional,
    Settlement,
}

#[derive(Copy, Clone, Debug, Serialize, Deserialize)]
pub struct WindowProfile {
    pub code: &'static str,
    pub reserve_floor_bps: u16,
    pub rollover_grace: u64,
    pub max_notes: usize,
    pub withdrawal_delay: u64,
    pub audit_weight: u16,
    pub settlement_label: &'static str,
    pub recommended_batch: BatchClass,
}

impl WindowProfile {
    pub fn accepts_note_count(&self, count: usize) -> bool {
        count <= self.max_notes
    }

    pub fn reserve_ratio(&self) -> f64 {
        f64::from(self.reserve_floor_bps) / 10_000.0
    }

    pub fn class_name(&self) -> &'static str {
        match self.recommended_batch {
            BatchClass::Micro => "micro",
            BatchClass::Small => "small",
            BatchClass::Medium => "medium",
            BatchClass::Institutional => "institutional",
            BatchClass::Settlement => "settlement",
        }
    }
}

pub const DEFAULT_PROFILE: WindowProfile = WindowProfile {
    code: "NW000",
    reserve_floor_bps: 750,
    rollover_grace: 2,
    max_notes: 64,
    withdrawal_delay: 1,
    audit_weight: 10,
    settlement_label: "nightfall-retail",
    recommended_batch: BatchClass::Small,
};

pub const WINDOW_PROFILES: &[WindowProfile] = &[
    WindowProfile {
        code: "NW000",
        reserve_floor_bps: 750,
        rollover_grace: 1,
        max_notes: 32,
        withdrawal_delay: 1,
        audit_weight: 10,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW001",
        reserve_floor_bps: 751,
        rollover_grace: 2,
        max_notes: 33,
        withdrawal_delay: 2,
        audit_weight: 11,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW002",
        reserve_floor_bps: 752,
        rollover_grace: 3,
        max_notes: 34,
        withdrawal_delay: 3,
        audit_weight: 12,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW003",
        reserve_floor_bps: 753,
        rollover_grace: 4,
        max_notes: 35,
        withdrawal_delay: 4,
        audit_weight: 13,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW004",
        reserve_floor_bps: 754,
        rollover_grace: 5,
        max_notes: 36,
        withdrawal_delay: 5,
        audit_weight: 14,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW005",
        reserve_floor_bps: 755,
        rollover_grace: 6,
        max_notes: 37,
        withdrawal_delay: 1,
        audit_weight: 15,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW006",
        reserve_floor_bps: 756,
        rollover_grace: 1,
        max_notes: 38,
        withdrawal_delay: 2,
        audit_weight: 16,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW007",
        reserve_floor_bps: 757,
        rollover_grace: 2,
        max_notes: 39,
        withdrawal_delay: 3,
        audit_weight: 17,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW008",
        reserve_floor_bps: 758,
        rollover_grace: 3,
        max_notes: 40,
        withdrawal_delay: 4,
        audit_weight: 18,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW009",
        reserve_floor_bps: 759,
        rollover_grace: 4,
        max_notes: 41,
        withdrawal_delay: 5,
        audit_weight: 19,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW010",
        reserve_floor_bps: 760,
        rollover_grace: 5,
        max_notes: 42,
        withdrawal_delay: 1,
        audit_weight: 20,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW011",
        reserve_floor_bps: 761,
        rollover_grace: 6,
        max_notes: 43,
        withdrawal_delay: 2,
        audit_weight: 21,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW012",
        reserve_floor_bps: 762,
        rollover_grace: 1,
        max_notes: 44,
        withdrawal_delay: 3,
        audit_weight: 22,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW013",
        reserve_floor_bps: 763,
        rollover_grace: 2,
        max_notes: 45,
        withdrawal_delay: 4,
        audit_weight: 23,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW014",
        reserve_floor_bps: 764,
        rollover_grace: 3,
        max_notes: 46,
        withdrawal_delay: 5,
        audit_weight: 24,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW015",
        reserve_floor_bps: 765,
        rollover_grace: 4,
        max_notes: 47,
        withdrawal_delay: 1,
        audit_weight: 25,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW016",
        reserve_floor_bps: 766,
        rollover_grace: 5,
        max_notes: 48,
        withdrawal_delay: 2,
        audit_weight: 26,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW017",
        reserve_floor_bps: 767,
        rollover_grace: 6,
        max_notes: 49,
        withdrawal_delay: 3,
        audit_weight: 27,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW018",
        reserve_floor_bps: 768,
        rollover_grace: 1,
        max_notes: 50,
        withdrawal_delay: 4,
        audit_weight: 28,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW019",
        reserve_floor_bps: 769,
        rollover_grace: 2,
        max_notes: 51,
        withdrawal_delay: 5,
        audit_weight: 29,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW020",
        reserve_floor_bps: 770,
        rollover_grace: 3,
        max_notes: 52,
        withdrawal_delay: 1,
        audit_weight: 30,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW021",
        reserve_floor_bps: 771,
        rollover_grace: 4,
        max_notes: 53,
        withdrawal_delay: 2,
        audit_weight: 31,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW022",
        reserve_floor_bps: 772,
        rollover_grace: 5,
        max_notes: 54,
        withdrawal_delay: 3,
        audit_weight: 32,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW023",
        reserve_floor_bps: 773,
        rollover_grace: 6,
        max_notes: 55,
        withdrawal_delay: 4,
        audit_weight: 33,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW024",
        reserve_floor_bps: 774,
        rollover_grace: 1,
        max_notes: 56,
        withdrawal_delay: 5,
        audit_weight: 34,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW025",
        reserve_floor_bps: 775,
        rollover_grace: 2,
        max_notes: 57,
        withdrawal_delay: 1,
        audit_weight: 35,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW026",
        reserve_floor_bps: 776,
        rollover_grace: 3,
        max_notes: 58,
        withdrawal_delay: 2,
        audit_weight: 36,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW027",
        reserve_floor_bps: 777,
        rollover_grace: 4,
        max_notes: 59,
        withdrawal_delay: 3,
        audit_weight: 37,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW028",
        reserve_floor_bps: 778,
        rollover_grace: 5,
        max_notes: 60,
        withdrawal_delay: 4,
        audit_weight: 38,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW029",
        reserve_floor_bps: 779,
        rollover_grace: 6,
        max_notes: 61,
        withdrawal_delay: 5,
        audit_weight: 39,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW030",
        reserve_floor_bps: 780,
        rollover_grace: 1,
        max_notes: 62,
        withdrawal_delay: 1,
        audit_weight: 40,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW031",
        reserve_floor_bps: 781,
        rollover_grace: 2,
        max_notes: 63,
        withdrawal_delay: 2,
        audit_weight: 41,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW032",
        reserve_floor_bps: 782,
        rollover_grace: 3,
        max_notes: 64,
        withdrawal_delay: 3,
        audit_weight: 42,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW033",
        reserve_floor_bps: 783,
        rollover_grace: 4,
        max_notes: 65,
        withdrawal_delay: 4,
        audit_weight: 43,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW034",
        reserve_floor_bps: 784,
        rollover_grace: 5,
        max_notes: 66,
        withdrawal_delay: 5,
        audit_weight: 44,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW035",
        reserve_floor_bps: 785,
        rollover_grace: 6,
        max_notes: 67,
        withdrawal_delay: 1,
        audit_weight: 45,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW036",
        reserve_floor_bps: 786,
        rollover_grace: 1,
        max_notes: 68,
        withdrawal_delay: 2,
        audit_weight: 46,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW037",
        reserve_floor_bps: 787,
        rollover_grace: 2,
        max_notes: 69,
        withdrawal_delay: 3,
        audit_weight: 47,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW038",
        reserve_floor_bps: 788,
        rollover_grace: 3,
        max_notes: 70,
        withdrawal_delay: 4,
        audit_weight: 48,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW039",
        reserve_floor_bps: 789,
        rollover_grace: 4,
        max_notes: 71,
        withdrawal_delay: 5,
        audit_weight: 49,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW040",
        reserve_floor_bps: 790,
        rollover_grace: 5,
        max_notes: 72,
        withdrawal_delay: 1,
        audit_weight: 10,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW041",
        reserve_floor_bps: 791,
        rollover_grace: 6,
        max_notes: 73,
        withdrawal_delay: 2,
        audit_weight: 11,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW042",
        reserve_floor_bps: 792,
        rollover_grace: 1,
        max_notes: 74,
        withdrawal_delay: 3,
        audit_weight: 12,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW043",
        reserve_floor_bps: 793,
        rollover_grace: 2,
        max_notes: 75,
        withdrawal_delay: 4,
        audit_weight: 13,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW044",
        reserve_floor_bps: 794,
        rollover_grace: 3,
        max_notes: 76,
        withdrawal_delay: 5,
        audit_weight: 14,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW045",
        reserve_floor_bps: 795,
        rollover_grace: 4,
        max_notes: 77,
        withdrawal_delay: 1,
        audit_weight: 15,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW046",
        reserve_floor_bps: 796,
        rollover_grace: 5,
        max_notes: 78,
        withdrawal_delay: 2,
        audit_weight: 16,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW047",
        reserve_floor_bps: 797,
        rollover_grace: 6,
        max_notes: 79,
        withdrawal_delay: 3,
        audit_weight: 17,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW048",
        reserve_floor_bps: 798,
        rollover_grace: 1,
        max_notes: 80,
        withdrawal_delay: 4,
        audit_weight: 18,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW049",
        reserve_floor_bps: 799,
        rollover_grace: 2,
        max_notes: 81,
        withdrawal_delay: 5,
        audit_weight: 19,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW050",
        reserve_floor_bps: 800,
        rollover_grace: 3,
        max_notes: 82,
        withdrawal_delay: 1,
        audit_weight: 20,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW051",
        reserve_floor_bps: 801,
        rollover_grace: 4,
        max_notes: 83,
        withdrawal_delay: 2,
        audit_weight: 21,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW052",
        reserve_floor_bps: 802,
        rollover_grace: 5,
        max_notes: 84,
        withdrawal_delay: 3,
        audit_weight: 22,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW053",
        reserve_floor_bps: 803,
        rollover_grace: 6,
        max_notes: 85,
        withdrawal_delay: 4,
        audit_weight: 23,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW054",
        reserve_floor_bps: 804,
        rollover_grace: 1,
        max_notes: 86,
        withdrawal_delay: 5,
        audit_weight: 24,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW055",
        reserve_floor_bps: 805,
        rollover_grace: 2,
        max_notes: 87,
        withdrawal_delay: 1,
        audit_weight: 25,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW056",
        reserve_floor_bps: 806,
        rollover_grace: 3,
        max_notes: 88,
        withdrawal_delay: 2,
        audit_weight: 26,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW057",
        reserve_floor_bps: 807,
        rollover_grace: 4,
        max_notes: 89,
        withdrawal_delay: 3,
        audit_weight: 27,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW058",
        reserve_floor_bps: 808,
        rollover_grace: 5,
        max_notes: 90,
        withdrawal_delay: 4,
        audit_weight: 28,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW059",
        reserve_floor_bps: 809,
        rollover_grace: 6,
        max_notes: 91,
        withdrawal_delay: 5,
        audit_weight: 29,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW060",
        reserve_floor_bps: 810,
        rollover_grace: 1,
        max_notes: 92,
        withdrawal_delay: 1,
        audit_weight: 30,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW061",
        reserve_floor_bps: 811,
        rollover_grace: 2,
        max_notes: 93,
        withdrawal_delay: 2,
        audit_weight: 31,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW062",
        reserve_floor_bps: 812,
        rollover_grace: 3,
        max_notes: 94,
        withdrawal_delay: 3,
        audit_weight: 32,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW063",
        reserve_floor_bps: 813,
        rollover_grace: 4,
        max_notes: 95,
        withdrawal_delay: 4,
        audit_weight: 33,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW064",
        reserve_floor_bps: 814,
        rollover_grace: 5,
        max_notes: 96,
        withdrawal_delay: 5,
        audit_weight: 34,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW065",
        reserve_floor_bps: 815,
        rollover_grace: 6,
        max_notes: 97,
        withdrawal_delay: 1,
        audit_weight: 35,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW066",
        reserve_floor_bps: 816,
        rollover_grace: 1,
        max_notes: 98,
        withdrawal_delay: 2,
        audit_weight: 36,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW067",
        reserve_floor_bps: 817,
        rollover_grace: 2,
        max_notes: 99,
        withdrawal_delay: 3,
        audit_weight: 37,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW068",
        reserve_floor_bps: 818,
        rollover_grace: 3,
        max_notes: 100,
        withdrawal_delay: 4,
        audit_weight: 38,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW069",
        reserve_floor_bps: 819,
        rollover_grace: 4,
        max_notes: 101,
        withdrawal_delay: 5,
        audit_weight: 39,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW070",
        reserve_floor_bps: 820,
        rollover_grace: 5,
        max_notes: 102,
        withdrawal_delay: 1,
        audit_weight: 40,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW071",
        reserve_floor_bps: 821,
        rollover_grace: 6,
        max_notes: 103,
        withdrawal_delay: 2,
        audit_weight: 41,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW072",
        reserve_floor_bps: 822,
        rollover_grace: 1,
        max_notes: 104,
        withdrawal_delay: 3,
        audit_weight: 42,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW073",
        reserve_floor_bps: 823,
        rollover_grace: 2,
        max_notes: 105,
        withdrawal_delay: 4,
        audit_weight: 43,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW074",
        reserve_floor_bps: 824,
        rollover_grace: 3,
        max_notes: 106,
        withdrawal_delay: 5,
        audit_weight: 44,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW075",
        reserve_floor_bps: 825,
        rollover_grace: 4,
        max_notes: 107,
        withdrawal_delay: 1,
        audit_weight: 45,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW076",
        reserve_floor_bps: 826,
        rollover_grace: 5,
        max_notes: 108,
        withdrawal_delay: 2,
        audit_weight: 46,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW077",
        reserve_floor_bps: 827,
        rollover_grace: 6,
        max_notes: 109,
        withdrawal_delay: 3,
        audit_weight: 47,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW078",
        reserve_floor_bps: 828,
        rollover_grace: 1,
        max_notes: 110,
        withdrawal_delay: 4,
        audit_weight: 48,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW079",
        reserve_floor_bps: 829,
        rollover_grace: 2,
        max_notes: 111,
        withdrawal_delay: 5,
        audit_weight: 49,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW080",
        reserve_floor_bps: 830,
        rollover_grace: 3,
        max_notes: 112,
        withdrawal_delay: 1,
        audit_weight: 10,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW081",
        reserve_floor_bps: 831,
        rollover_grace: 4,
        max_notes: 113,
        withdrawal_delay: 2,
        audit_weight: 11,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW082",
        reserve_floor_bps: 832,
        rollover_grace: 5,
        max_notes: 114,
        withdrawal_delay: 3,
        audit_weight: 12,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW083",
        reserve_floor_bps: 833,
        rollover_grace: 6,
        max_notes: 115,
        withdrawal_delay: 4,
        audit_weight: 13,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW084",
        reserve_floor_bps: 834,
        rollover_grace: 1,
        max_notes: 116,
        withdrawal_delay: 5,
        audit_weight: 14,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW085",
        reserve_floor_bps: 835,
        rollover_grace: 2,
        max_notes: 117,
        withdrawal_delay: 1,
        audit_weight: 15,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW086",
        reserve_floor_bps: 836,
        rollover_grace: 3,
        max_notes: 118,
        withdrawal_delay: 2,
        audit_weight: 16,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW087",
        reserve_floor_bps: 837,
        rollover_grace: 4,
        max_notes: 119,
        withdrawal_delay: 3,
        audit_weight: 17,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW088",
        reserve_floor_bps: 838,
        rollover_grace: 5,
        max_notes: 120,
        withdrawal_delay: 4,
        audit_weight: 18,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW089",
        reserve_floor_bps: 839,
        rollover_grace: 6,
        max_notes: 121,
        withdrawal_delay: 5,
        audit_weight: 19,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW090",
        reserve_floor_bps: 750,
        rollover_grace: 1,
        max_notes: 122,
        withdrawal_delay: 1,
        audit_weight: 20,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW091",
        reserve_floor_bps: 751,
        rollover_grace: 2,
        max_notes: 123,
        withdrawal_delay: 2,
        audit_weight: 21,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW092",
        reserve_floor_bps: 752,
        rollover_grace: 3,
        max_notes: 124,
        withdrawal_delay: 3,
        audit_weight: 22,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW093",
        reserve_floor_bps: 753,
        rollover_grace: 4,
        max_notes: 125,
        withdrawal_delay: 4,
        audit_weight: 23,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW094",
        reserve_floor_bps: 754,
        rollover_grace: 5,
        max_notes: 126,
        withdrawal_delay: 5,
        audit_weight: 24,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW095",
        reserve_floor_bps: 755,
        rollover_grace: 6,
        max_notes: 127,
        withdrawal_delay: 1,
        audit_weight: 25,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW096",
        reserve_floor_bps: 756,
        rollover_grace: 1,
        max_notes: 128,
        withdrawal_delay: 2,
        audit_weight: 26,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW097",
        reserve_floor_bps: 757,
        rollover_grace: 2,
        max_notes: 129,
        withdrawal_delay: 3,
        audit_weight: 27,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW098",
        reserve_floor_bps: 758,
        rollover_grace: 3,
        max_notes: 130,
        withdrawal_delay: 4,
        audit_weight: 28,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW099",
        reserve_floor_bps: 759,
        rollover_grace: 4,
        max_notes: 131,
        withdrawal_delay: 5,
        audit_weight: 29,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW100",
        reserve_floor_bps: 760,
        rollover_grace: 5,
        max_notes: 132,
        withdrawal_delay: 1,
        audit_weight: 30,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW101",
        reserve_floor_bps: 761,
        rollover_grace: 6,
        max_notes: 133,
        withdrawal_delay: 2,
        audit_weight: 31,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW102",
        reserve_floor_bps: 762,
        rollover_grace: 1,
        max_notes: 134,
        withdrawal_delay: 3,
        audit_weight: 32,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW103",
        reserve_floor_bps: 763,
        rollover_grace: 2,
        max_notes: 135,
        withdrawal_delay: 4,
        audit_weight: 33,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW104",
        reserve_floor_bps: 764,
        rollover_grace: 3,
        max_notes: 136,
        withdrawal_delay: 5,
        audit_weight: 34,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW105",
        reserve_floor_bps: 765,
        rollover_grace: 4,
        max_notes: 137,
        withdrawal_delay: 1,
        audit_weight: 35,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW106",
        reserve_floor_bps: 766,
        rollover_grace: 5,
        max_notes: 138,
        withdrawal_delay: 2,
        audit_weight: 36,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW107",
        reserve_floor_bps: 767,
        rollover_grace: 6,
        max_notes: 139,
        withdrawal_delay: 3,
        audit_weight: 37,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW108",
        reserve_floor_bps: 768,
        rollover_grace: 1,
        max_notes: 140,
        withdrawal_delay: 4,
        audit_weight: 38,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW109",
        reserve_floor_bps: 769,
        rollover_grace: 2,
        max_notes: 141,
        withdrawal_delay: 5,
        audit_weight: 39,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW110",
        reserve_floor_bps: 770,
        rollover_grace: 3,
        max_notes: 142,
        withdrawal_delay: 1,
        audit_weight: 40,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW111",
        reserve_floor_bps: 771,
        rollover_grace: 4,
        max_notes: 143,
        withdrawal_delay: 2,
        audit_weight: 41,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW112",
        reserve_floor_bps: 772,
        rollover_grace: 5,
        max_notes: 144,
        withdrawal_delay: 3,
        audit_weight: 42,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW113",
        reserve_floor_bps: 773,
        rollover_grace: 6,
        max_notes: 145,
        withdrawal_delay: 4,
        audit_weight: 43,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW114",
        reserve_floor_bps: 774,
        rollover_grace: 1,
        max_notes: 146,
        withdrawal_delay: 5,
        audit_weight: 44,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW115",
        reserve_floor_bps: 775,
        rollover_grace: 2,
        max_notes: 147,
        withdrawal_delay: 1,
        audit_weight: 45,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW116",
        reserve_floor_bps: 776,
        rollover_grace: 3,
        max_notes: 148,
        withdrawal_delay: 2,
        audit_weight: 46,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW117",
        reserve_floor_bps: 777,
        rollover_grace: 4,
        max_notes: 149,
        withdrawal_delay: 3,
        audit_weight: 47,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW118",
        reserve_floor_bps: 778,
        rollover_grace: 5,
        max_notes: 150,
        withdrawal_delay: 4,
        audit_weight: 48,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW119",
        reserve_floor_bps: 779,
        rollover_grace: 6,
        max_notes: 151,
        withdrawal_delay: 5,
        audit_weight: 49,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW120",
        reserve_floor_bps: 780,
        rollover_grace: 1,
        max_notes: 152,
        withdrawal_delay: 1,
        audit_weight: 10,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW121",
        reserve_floor_bps: 781,
        rollover_grace: 2,
        max_notes: 153,
        withdrawal_delay: 2,
        audit_weight: 11,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW122",
        reserve_floor_bps: 782,
        rollover_grace: 3,
        max_notes: 154,
        withdrawal_delay: 3,
        audit_weight: 12,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW123",
        reserve_floor_bps: 783,
        rollover_grace: 4,
        max_notes: 155,
        withdrawal_delay: 4,
        audit_weight: 13,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW124",
        reserve_floor_bps: 784,
        rollover_grace: 5,
        max_notes: 156,
        withdrawal_delay: 5,
        audit_weight: 14,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW125",
        reserve_floor_bps: 785,
        rollover_grace: 6,
        max_notes: 157,
        withdrawal_delay: 1,
        audit_weight: 15,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW126",
        reserve_floor_bps: 786,
        rollover_grace: 1,
        max_notes: 158,
        withdrawal_delay: 2,
        audit_weight: 16,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW127",
        reserve_floor_bps: 787,
        rollover_grace: 2,
        max_notes: 159,
        withdrawal_delay: 3,
        audit_weight: 17,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW128",
        reserve_floor_bps: 788,
        rollover_grace: 3,
        max_notes: 32,
        withdrawal_delay: 4,
        audit_weight: 18,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW129",
        reserve_floor_bps: 789,
        rollover_grace: 4,
        max_notes: 33,
        withdrawal_delay: 5,
        audit_weight: 19,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW130",
        reserve_floor_bps: 790,
        rollover_grace: 5,
        max_notes: 34,
        withdrawal_delay: 1,
        audit_weight: 20,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW131",
        reserve_floor_bps: 791,
        rollover_grace: 6,
        max_notes: 35,
        withdrawal_delay: 2,
        audit_weight: 21,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW132",
        reserve_floor_bps: 792,
        rollover_grace: 1,
        max_notes: 36,
        withdrawal_delay: 3,
        audit_weight: 22,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW133",
        reserve_floor_bps: 793,
        rollover_grace: 2,
        max_notes: 37,
        withdrawal_delay: 4,
        audit_weight: 23,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW134",
        reserve_floor_bps: 794,
        rollover_grace: 3,
        max_notes: 38,
        withdrawal_delay: 5,
        audit_weight: 24,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW135",
        reserve_floor_bps: 795,
        rollover_grace: 4,
        max_notes: 39,
        withdrawal_delay: 1,
        audit_weight: 25,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW136",
        reserve_floor_bps: 796,
        rollover_grace: 5,
        max_notes: 40,
        withdrawal_delay: 2,
        audit_weight: 26,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW137",
        reserve_floor_bps: 797,
        rollover_grace: 6,
        max_notes: 41,
        withdrawal_delay: 3,
        audit_weight: 27,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW138",
        reserve_floor_bps: 798,
        rollover_grace: 1,
        max_notes: 42,
        withdrawal_delay: 4,
        audit_weight: 28,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW139",
        reserve_floor_bps: 799,
        rollover_grace: 2,
        max_notes: 43,
        withdrawal_delay: 5,
        audit_weight: 29,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW140",
        reserve_floor_bps: 800,
        rollover_grace: 3,
        max_notes: 44,
        withdrawal_delay: 1,
        audit_weight: 30,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW141",
        reserve_floor_bps: 801,
        rollover_grace: 4,
        max_notes: 45,
        withdrawal_delay: 2,
        audit_weight: 31,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW142",
        reserve_floor_bps: 802,
        rollover_grace: 5,
        max_notes: 46,
        withdrawal_delay: 3,
        audit_weight: 32,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW143",
        reserve_floor_bps: 803,
        rollover_grace: 6,
        max_notes: 47,
        withdrawal_delay: 4,
        audit_weight: 33,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW144",
        reserve_floor_bps: 804,
        rollover_grace: 1,
        max_notes: 48,
        withdrawal_delay: 5,
        audit_weight: 34,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW145",
        reserve_floor_bps: 805,
        rollover_grace: 2,
        max_notes: 49,
        withdrawal_delay: 1,
        audit_weight: 35,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW146",
        reserve_floor_bps: 806,
        rollover_grace: 3,
        max_notes: 50,
        withdrawal_delay: 2,
        audit_weight: 36,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW147",
        reserve_floor_bps: 807,
        rollover_grace: 4,
        max_notes: 51,
        withdrawal_delay: 3,
        audit_weight: 37,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW148",
        reserve_floor_bps: 808,
        rollover_grace: 5,
        max_notes: 52,
        withdrawal_delay: 4,
        audit_weight: 38,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW149",
        reserve_floor_bps: 809,
        rollover_grace: 6,
        max_notes: 53,
        withdrawal_delay: 5,
        audit_weight: 39,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW150",
        reserve_floor_bps: 810,
        rollover_grace: 1,
        max_notes: 54,
        withdrawal_delay: 1,
        audit_weight: 40,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW151",
        reserve_floor_bps: 811,
        rollover_grace: 2,
        max_notes: 55,
        withdrawal_delay: 2,
        audit_weight: 41,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW152",
        reserve_floor_bps: 812,
        rollover_grace: 3,
        max_notes: 56,
        withdrawal_delay: 3,
        audit_weight: 42,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW153",
        reserve_floor_bps: 813,
        rollover_grace: 4,
        max_notes: 57,
        withdrawal_delay: 4,
        audit_weight: 43,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW154",
        reserve_floor_bps: 814,
        rollover_grace: 5,
        max_notes: 58,
        withdrawal_delay: 5,
        audit_weight: 44,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW155",
        reserve_floor_bps: 815,
        rollover_grace: 6,
        max_notes: 59,
        withdrawal_delay: 1,
        audit_weight: 45,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW156",
        reserve_floor_bps: 816,
        rollover_grace: 1,
        max_notes: 60,
        withdrawal_delay: 2,
        audit_weight: 46,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW157",
        reserve_floor_bps: 817,
        rollover_grace: 2,
        max_notes: 61,
        withdrawal_delay: 3,
        audit_weight: 47,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW158",
        reserve_floor_bps: 818,
        rollover_grace: 3,
        max_notes: 62,
        withdrawal_delay: 4,
        audit_weight: 48,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW159",
        reserve_floor_bps: 819,
        rollover_grace: 4,
        max_notes: 63,
        withdrawal_delay: 5,
        audit_weight: 49,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW160",
        reserve_floor_bps: 820,
        rollover_grace: 5,
        max_notes: 64,
        withdrawal_delay: 1,
        audit_weight: 10,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW161",
        reserve_floor_bps: 821,
        rollover_grace: 6,
        max_notes: 65,
        withdrawal_delay: 2,
        audit_weight: 11,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW162",
        reserve_floor_bps: 822,
        rollover_grace: 1,
        max_notes: 66,
        withdrawal_delay: 3,
        audit_weight: 12,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW163",
        reserve_floor_bps: 823,
        rollover_grace: 2,
        max_notes: 67,
        withdrawal_delay: 4,
        audit_weight: 13,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW164",
        reserve_floor_bps: 824,
        rollover_grace: 3,
        max_notes: 68,
        withdrawal_delay: 5,
        audit_weight: 14,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW165",
        reserve_floor_bps: 825,
        rollover_grace: 4,
        max_notes: 69,
        withdrawal_delay: 1,
        audit_weight: 15,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW166",
        reserve_floor_bps: 826,
        rollover_grace: 5,
        max_notes: 70,
        withdrawal_delay: 2,
        audit_weight: 16,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW167",
        reserve_floor_bps: 827,
        rollover_grace: 6,
        max_notes: 71,
        withdrawal_delay: 3,
        audit_weight: 17,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW168",
        reserve_floor_bps: 828,
        rollover_grace: 1,
        max_notes: 72,
        withdrawal_delay: 4,
        audit_weight: 18,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW169",
        reserve_floor_bps: 829,
        rollover_grace: 2,
        max_notes: 73,
        withdrawal_delay: 5,
        audit_weight: 19,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW170",
        reserve_floor_bps: 830,
        rollover_grace: 3,
        max_notes: 74,
        withdrawal_delay: 1,
        audit_weight: 20,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW171",
        reserve_floor_bps: 831,
        rollover_grace: 4,
        max_notes: 75,
        withdrawal_delay: 2,
        audit_weight: 21,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW172",
        reserve_floor_bps: 832,
        rollover_grace: 5,
        max_notes: 76,
        withdrawal_delay: 3,
        audit_weight: 22,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW173",
        reserve_floor_bps: 833,
        rollover_grace: 6,
        max_notes: 77,
        withdrawal_delay: 4,
        audit_weight: 23,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW174",
        reserve_floor_bps: 834,
        rollover_grace: 1,
        max_notes: 78,
        withdrawal_delay: 5,
        audit_weight: 24,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW175",
        reserve_floor_bps: 835,
        rollover_grace: 2,
        max_notes: 79,
        withdrawal_delay: 1,
        audit_weight: 25,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW176",
        reserve_floor_bps: 836,
        rollover_grace: 3,
        max_notes: 80,
        withdrawal_delay: 2,
        audit_weight: 26,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW177",
        reserve_floor_bps: 837,
        rollover_grace: 4,
        max_notes: 81,
        withdrawal_delay: 3,
        audit_weight: 27,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW178",
        reserve_floor_bps: 838,
        rollover_grace: 5,
        max_notes: 82,
        withdrawal_delay: 4,
        audit_weight: 28,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW179",
        reserve_floor_bps: 839,
        rollover_grace: 6,
        max_notes: 83,
        withdrawal_delay: 5,
        audit_weight: 29,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW180",
        reserve_floor_bps: 750,
        rollover_grace: 1,
        max_notes: 84,
        withdrawal_delay: 1,
        audit_weight: 30,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW181",
        reserve_floor_bps: 751,
        rollover_grace: 2,
        max_notes: 85,
        withdrawal_delay: 2,
        audit_weight: 31,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW182",
        reserve_floor_bps: 752,
        rollover_grace: 3,
        max_notes: 86,
        withdrawal_delay: 3,
        audit_weight: 32,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW183",
        reserve_floor_bps: 753,
        rollover_grace: 4,
        max_notes: 87,
        withdrawal_delay: 4,
        audit_weight: 33,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW184",
        reserve_floor_bps: 754,
        rollover_grace: 5,
        max_notes: 88,
        withdrawal_delay: 5,
        audit_weight: 34,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW185",
        reserve_floor_bps: 755,
        rollover_grace: 6,
        max_notes: 89,
        withdrawal_delay: 1,
        audit_weight: 35,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW186",
        reserve_floor_bps: 756,
        rollover_grace: 1,
        max_notes: 90,
        withdrawal_delay: 2,
        audit_weight: 36,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW187",
        reserve_floor_bps: 757,
        rollover_grace: 2,
        max_notes: 91,
        withdrawal_delay: 3,
        audit_weight: 37,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW188",
        reserve_floor_bps: 758,
        rollover_grace: 3,
        max_notes: 92,
        withdrawal_delay: 4,
        audit_weight: 38,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW189",
        reserve_floor_bps: 759,
        rollover_grace: 4,
        max_notes: 93,
        withdrawal_delay: 5,
        audit_weight: 39,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW190",
        reserve_floor_bps: 760,
        rollover_grace: 5,
        max_notes: 94,
        withdrawal_delay: 1,
        audit_weight: 40,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW191",
        reserve_floor_bps: 761,
        rollover_grace: 6,
        max_notes: 95,
        withdrawal_delay: 2,
        audit_weight: 41,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW192",
        reserve_floor_bps: 762,
        rollover_grace: 1,
        max_notes: 96,
        withdrawal_delay: 3,
        audit_weight: 42,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW193",
        reserve_floor_bps: 763,
        rollover_grace: 2,
        max_notes: 97,
        withdrawal_delay: 4,
        audit_weight: 43,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW194",
        reserve_floor_bps: 764,
        rollover_grace: 3,
        max_notes: 98,
        withdrawal_delay: 5,
        audit_weight: 44,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW195",
        reserve_floor_bps: 765,
        rollover_grace: 4,
        max_notes: 99,
        withdrawal_delay: 1,
        audit_weight: 45,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW196",
        reserve_floor_bps: 766,
        rollover_grace: 5,
        max_notes: 100,
        withdrawal_delay: 2,
        audit_weight: 46,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW197",
        reserve_floor_bps: 767,
        rollover_grace: 6,
        max_notes: 101,
        withdrawal_delay: 3,
        audit_weight: 47,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW198",
        reserve_floor_bps: 768,
        rollover_grace: 1,
        max_notes: 102,
        withdrawal_delay: 4,
        audit_weight: 48,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW199",
        reserve_floor_bps: 769,
        rollover_grace: 2,
        max_notes: 103,
        withdrawal_delay: 5,
        audit_weight: 49,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW200",
        reserve_floor_bps: 770,
        rollover_grace: 3,
        max_notes: 104,
        withdrawal_delay: 1,
        audit_weight: 10,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW201",
        reserve_floor_bps: 771,
        rollover_grace: 4,
        max_notes: 105,
        withdrawal_delay: 2,
        audit_weight: 11,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW202",
        reserve_floor_bps: 772,
        rollover_grace: 5,
        max_notes: 106,
        withdrawal_delay: 3,
        audit_weight: 12,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW203",
        reserve_floor_bps: 773,
        rollover_grace: 6,
        max_notes: 107,
        withdrawal_delay: 4,
        audit_weight: 13,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW204",
        reserve_floor_bps: 774,
        rollover_grace: 1,
        max_notes: 108,
        withdrawal_delay: 5,
        audit_weight: 14,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW205",
        reserve_floor_bps: 775,
        rollover_grace: 2,
        max_notes: 109,
        withdrawal_delay: 1,
        audit_weight: 15,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW206",
        reserve_floor_bps: 776,
        rollover_grace: 3,
        max_notes: 110,
        withdrawal_delay: 2,
        audit_weight: 16,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW207",
        reserve_floor_bps: 777,
        rollover_grace: 4,
        max_notes: 111,
        withdrawal_delay: 3,
        audit_weight: 17,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW208",
        reserve_floor_bps: 778,
        rollover_grace: 5,
        max_notes: 112,
        withdrawal_delay: 4,
        audit_weight: 18,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW209",
        reserve_floor_bps: 779,
        rollover_grace: 6,
        max_notes: 113,
        withdrawal_delay: 5,
        audit_weight: 19,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW210",
        reserve_floor_bps: 780,
        rollover_grace: 1,
        max_notes: 114,
        withdrawal_delay: 1,
        audit_weight: 20,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW211",
        reserve_floor_bps: 781,
        rollover_grace: 2,
        max_notes: 115,
        withdrawal_delay: 2,
        audit_weight: 21,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW212",
        reserve_floor_bps: 782,
        rollover_grace: 3,
        max_notes: 116,
        withdrawal_delay: 3,
        audit_weight: 22,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW213",
        reserve_floor_bps: 783,
        rollover_grace: 4,
        max_notes: 117,
        withdrawal_delay: 4,
        audit_weight: 23,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW214",
        reserve_floor_bps: 784,
        rollover_grace: 5,
        max_notes: 118,
        withdrawal_delay: 5,
        audit_weight: 24,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW215",
        reserve_floor_bps: 785,
        rollover_grace: 6,
        max_notes: 119,
        withdrawal_delay: 1,
        audit_weight: 25,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW216",
        reserve_floor_bps: 786,
        rollover_grace: 1,
        max_notes: 120,
        withdrawal_delay: 2,
        audit_weight: 26,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW217",
        reserve_floor_bps: 787,
        rollover_grace: 2,
        max_notes: 121,
        withdrawal_delay: 3,
        audit_weight: 27,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW218",
        reserve_floor_bps: 788,
        rollover_grace: 3,
        max_notes: 122,
        withdrawal_delay: 4,
        audit_weight: 28,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW219",
        reserve_floor_bps: 789,
        rollover_grace: 4,
        max_notes: 123,
        withdrawal_delay: 5,
        audit_weight: 29,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW220",
        reserve_floor_bps: 790,
        rollover_grace: 5,
        max_notes: 124,
        withdrawal_delay: 1,
        audit_weight: 30,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW221",
        reserve_floor_bps: 791,
        rollover_grace: 6,
        max_notes: 125,
        withdrawal_delay: 2,
        audit_weight: 31,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW222",
        reserve_floor_bps: 792,
        rollover_grace: 1,
        max_notes: 126,
        withdrawal_delay: 3,
        audit_weight: 32,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW223",
        reserve_floor_bps: 793,
        rollover_grace: 2,
        max_notes: 127,
        withdrawal_delay: 4,
        audit_weight: 33,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW224",
        reserve_floor_bps: 794,
        rollover_grace: 3,
        max_notes: 128,
        withdrawal_delay: 5,
        audit_weight: 34,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW225",
        reserve_floor_bps: 795,
        rollover_grace: 4,
        max_notes: 129,
        withdrawal_delay: 1,
        audit_weight: 35,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW226",
        reserve_floor_bps: 796,
        rollover_grace: 5,
        max_notes: 130,
        withdrawal_delay: 2,
        audit_weight: 36,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW227",
        reserve_floor_bps: 797,
        rollover_grace: 6,
        max_notes: 131,
        withdrawal_delay: 3,
        audit_weight: 37,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW228",
        reserve_floor_bps: 798,
        rollover_grace: 1,
        max_notes: 132,
        withdrawal_delay: 4,
        audit_weight: 38,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW229",
        reserve_floor_bps: 799,
        rollover_grace: 2,
        max_notes: 133,
        withdrawal_delay: 5,
        audit_weight: 39,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW230",
        reserve_floor_bps: 800,
        rollover_grace: 3,
        max_notes: 134,
        withdrawal_delay: 1,
        audit_weight: 40,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW231",
        reserve_floor_bps: 801,
        rollover_grace: 4,
        max_notes: 135,
        withdrawal_delay: 2,
        audit_weight: 41,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW232",
        reserve_floor_bps: 802,
        rollover_grace: 5,
        max_notes: 136,
        withdrawal_delay: 3,
        audit_weight: 42,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW233",
        reserve_floor_bps: 803,
        rollover_grace: 6,
        max_notes: 137,
        withdrawal_delay: 4,
        audit_weight: 43,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW234",
        reserve_floor_bps: 804,
        rollover_grace: 1,
        max_notes: 138,
        withdrawal_delay: 5,
        audit_weight: 44,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW235",
        reserve_floor_bps: 805,
        rollover_grace: 2,
        max_notes: 139,
        withdrawal_delay: 1,
        audit_weight: 45,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW236",
        reserve_floor_bps: 806,
        rollover_grace: 3,
        max_notes: 140,
        withdrawal_delay: 2,
        audit_weight: 46,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW237",
        reserve_floor_bps: 807,
        rollover_grace: 4,
        max_notes: 141,
        withdrawal_delay: 3,
        audit_weight: 47,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW238",
        reserve_floor_bps: 808,
        rollover_grace: 5,
        max_notes: 142,
        withdrawal_delay: 4,
        audit_weight: 48,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW239",
        reserve_floor_bps: 809,
        rollover_grace: 6,
        max_notes: 143,
        withdrawal_delay: 5,
        audit_weight: 49,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW240",
        reserve_floor_bps: 810,
        rollover_grace: 1,
        max_notes: 144,
        withdrawal_delay: 1,
        audit_weight: 10,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW241",
        reserve_floor_bps: 811,
        rollover_grace: 2,
        max_notes: 145,
        withdrawal_delay: 2,
        audit_weight: 11,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW242",
        reserve_floor_bps: 812,
        rollover_grace: 3,
        max_notes: 146,
        withdrawal_delay: 3,
        audit_weight: 12,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW243",
        reserve_floor_bps: 813,
        rollover_grace: 4,
        max_notes: 147,
        withdrawal_delay: 4,
        audit_weight: 13,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW244",
        reserve_floor_bps: 814,
        rollover_grace: 5,
        max_notes: 148,
        withdrawal_delay: 5,
        audit_weight: 14,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW245",
        reserve_floor_bps: 815,
        rollover_grace: 6,
        max_notes: 149,
        withdrawal_delay: 1,
        audit_weight: 15,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW246",
        reserve_floor_bps: 816,
        rollover_grace: 1,
        max_notes: 150,
        withdrawal_delay: 2,
        audit_weight: 16,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW247",
        reserve_floor_bps: 817,
        rollover_grace: 2,
        max_notes: 151,
        withdrawal_delay: 3,
        audit_weight: 17,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW248",
        reserve_floor_bps: 818,
        rollover_grace: 3,
        max_notes: 152,
        withdrawal_delay: 4,
        audit_weight: 18,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW249",
        reserve_floor_bps: 819,
        rollover_grace: 4,
        max_notes: 153,
        withdrawal_delay: 5,
        audit_weight: 19,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW250",
        reserve_floor_bps: 820,
        rollover_grace: 5,
        max_notes: 154,
        withdrawal_delay: 1,
        audit_weight: 20,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW251",
        reserve_floor_bps: 821,
        rollover_grace: 6,
        max_notes: 155,
        withdrawal_delay: 2,
        audit_weight: 21,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW252",
        reserve_floor_bps: 822,
        rollover_grace: 1,
        max_notes: 156,
        withdrawal_delay: 3,
        audit_weight: 22,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW253",
        reserve_floor_bps: 823,
        rollover_grace: 2,
        max_notes: 157,
        withdrawal_delay: 4,
        audit_weight: 23,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW254",
        reserve_floor_bps: 824,
        rollover_grace: 3,
        max_notes: 158,
        withdrawal_delay: 5,
        audit_weight: 24,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW255",
        reserve_floor_bps: 825,
        rollover_grace: 4,
        max_notes: 159,
        withdrawal_delay: 1,
        audit_weight: 25,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW256",
        reserve_floor_bps: 826,
        rollover_grace: 5,
        max_notes: 32,
        withdrawal_delay: 2,
        audit_weight: 26,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW257",
        reserve_floor_bps: 827,
        rollover_grace: 6,
        max_notes: 33,
        withdrawal_delay: 3,
        audit_weight: 27,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW258",
        reserve_floor_bps: 828,
        rollover_grace: 1,
        max_notes: 34,
        withdrawal_delay: 4,
        audit_weight: 28,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW259",
        reserve_floor_bps: 829,
        rollover_grace: 2,
        max_notes: 35,
        withdrawal_delay: 5,
        audit_weight: 29,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW260",
        reserve_floor_bps: 830,
        rollover_grace: 3,
        max_notes: 36,
        withdrawal_delay: 1,
        audit_weight: 30,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW261",
        reserve_floor_bps: 831,
        rollover_grace: 4,
        max_notes: 37,
        withdrawal_delay: 2,
        audit_weight: 31,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW262",
        reserve_floor_bps: 832,
        rollover_grace: 5,
        max_notes: 38,
        withdrawal_delay: 3,
        audit_weight: 32,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW263",
        reserve_floor_bps: 833,
        rollover_grace: 6,
        max_notes: 39,
        withdrawal_delay: 4,
        audit_weight: 33,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW264",
        reserve_floor_bps: 834,
        rollover_grace: 1,
        max_notes: 40,
        withdrawal_delay: 5,
        audit_weight: 34,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW265",
        reserve_floor_bps: 835,
        rollover_grace: 2,
        max_notes: 41,
        withdrawal_delay: 1,
        audit_weight: 35,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW266",
        reserve_floor_bps: 836,
        rollover_grace: 3,
        max_notes: 42,
        withdrawal_delay: 2,
        audit_weight: 36,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW267",
        reserve_floor_bps: 837,
        rollover_grace: 4,
        max_notes: 43,
        withdrawal_delay: 3,
        audit_weight: 37,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW268",
        reserve_floor_bps: 838,
        rollover_grace: 5,
        max_notes: 44,
        withdrawal_delay: 4,
        audit_weight: 38,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW269",
        reserve_floor_bps: 839,
        rollover_grace: 6,
        max_notes: 45,
        withdrawal_delay: 5,
        audit_weight: 39,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW270",
        reserve_floor_bps: 750,
        rollover_grace: 1,
        max_notes: 46,
        withdrawal_delay: 1,
        audit_weight: 40,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW271",
        reserve_floor_bps: 751,
        rollover_grace: 2,
        max_notes: 47,
        withdrawal_delay: 2,
        audit_weight: 41,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW272",
        reserve_floor_bps: 752,
        rollover_grace: 3,
        max_notes: 48,
        withdrawal_delay: 3,
        audit_weight: 42,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW273",
        reserve_floor_bps: 753,
        rollover_grace: 4,
        max_notes: 49,
        withdrawal_delay: 4,
        audit_weight: 43,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW274",
        reserve_floor_bps: 754,
        rollover_grace: 5,
        max_notes: 50,
        withdrawal_delay: 5,
        audit_weight: 44,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW275",
        reserve_floor_bps: 755,
        rollover_grace: 6,
        max_notes: 51,
        withdrawal_delay: 1,
        audit_weight: 45,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW276",
        reserve_floor_bps: 756,
        rollover_grace: 1,
        max_notes: 52,
        withdrawal_delay: 2,
        audit_weight: 46,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW277",
        reserve_floor_bps: 757,
        rollover_grace: 2,
        max_notes: 53,
        withdrawal_delay: 3,
        audit_weight: 47,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW278",
        reserve_floor_bps: 758,
        rollover_grace: 3,
        max_notes: 54,
        withdrawal_delay: 4,
        audit_weight: 48,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW279",
        reserve_floor_bps: 759,
        rollover_grace: 4,
        max_notes: 55,
        withdrawal_delay: 5,
        audit_weight: 49,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW280",
        reserve_floor_bps: 760,
        rollover_grace: 5,
        max_notes: 56,
        withdrawal_delay: 1,
        audit_weight: 10,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW281",
        reserve_floor_bps: 761,
        rollover_grace: 6,
        max_notes: 57,
        withdrawal_delay: 2,
        audit_weight: 11,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW282",
        reserve_floor_bps: 762,
        rollover_grace: 1,
        max_notes: 58,
        withdrawal_delay: 3,
        audit_weight: 12,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW283",
        reserve_floor_bps: 763,
        rollover_grace: 2,
        max_notes: 59,
        withdrawal_delay: 4,
        audit_weight: 13,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW284",
        reserve_floor_bps: 764,
        rollover_grace: 3,
        max_notes: 60,
        withdrawal_delay: 5,
        audit_weight: 14,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW285",
        reserve_floor_bps: 765,
        rollover_grace: 4,
        max_notes: 61,
        withdrawal_delay: 1,
        audit_weight: 15,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW286",
        reserve_floor_bps: 766,
        rollover_grace: 5,
        max_notes: 62,
        withdrawal_delay: 2,
        audit_weight: 16,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW287",
        reserve_floor_bps: 767,
        rollover_grace: 6,
        max_notes: 63,
        withdrawal_delay: 3,
        audit_weight: 17,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW288",
        reserve_floor_bps: 768,
        rollover_grace: 1,
        max_notes: 64,
        withdrawal_delay: 4,
        audit_weight: 18,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW289",
        reserve_floor_bps: 769,
        rollover_grace: 2,
        max_notes: 65,
        withdrawal_delay: 5,
        audit_weight: 19,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW290",
        reserve_floor_bps: 770,
        rollover_grace: 3,
        max_notes: 66,
        withdrawal_delay: 1,
        audit_weight: 20,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW291",
        reserve_floor_bps: 771,
        rollover_grace: 4,
        max_notes: 67,
        withdrawal_delay: 2,
        audit_weight: 21,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW292",
        reserve_floor_bps: 772,
        rollover_grace: 5,
        max_notes: 68,
        withdrawal_delay: 3,
        audit_weight: 22,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW293",
        reserve_floor_bps: 773,
        rollover_grace: 6,
        max_notes: 69,
        withdrawal_delay: 4,
        audit_weight: 23,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW294",
        reserve_floor_bps: 774,
        rollover_grace: 1,
        max_notes: 70,
        withdrawal_delay: 5,
        audit_weight: 24,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW295",
        reserve_floor_bps: 775,
        rollover_grace: 2,
        max_notes: 71,
        withdrawal_delay: 1,
        audit_weight: 25,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW296",
        reserve_floor_bps: 776,
        rollover_grace: 3,
        max_notes: 72,
        withdrawal_delay: 2,
        audit_weight: 26,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW297",
        reserve_floor_bps: 777,
        rollover_grace: 4,
        max_notes: 73,
        withdrawal_delay: 3,
        audit_weight: 27,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW298",
        reserve_floor_bps: 778,
        rollover_grace: 5,
        max_notes: 74,
        withdrawal_delay: 4,
        audit_weight: 28,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW299",
        reserve_floor_bps: 779,
        rollover_grace: 6,
        max_notes: 75,
        withdrawal_delay: 5,
        audit_weight: 29,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW300",
        reserve_floor_bps: 780,
        rollover_grace: 1,
        max_notes: 76,
        withdrawal_delay: 1,
        audit_weight: 30,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW301",
        reserve_floor_bps: 781,
        rollover_grace: 2,
        max_notes: 77,
        withdrawal_delay: 2,
        audit_weight: 31,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW302",
        reserve_floor_bps: 782,
        rollover_grace: 3,
        max_notes: 78,
        withdrawal_delay: 3,
        audit_weight: 32,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW303",
        reserve_floor_bps: 783,
        rollover_grace: 4,
        max_notes: 79,
        withdrawal_delay: 4,
        audit_weight: 33,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW304",
        reserve_floor_bps: 784,
        rollover_grace: 5,
        max_notes: 80,
        withdrawal_delay: 5,
        audit_weight: 34,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW305",
        reserve_floor_bps: 785,
        rollover_grace: 6,
        max_notes: 81,
        withdrawal_delay: 1,
        audit_weight: 35,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW306",
        reserve_floor_bps: 786,
        rollover_grace: 1,
        max_notes: 82,
        withdrawal_delay: 2,
        audit_weight: 36,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW307",
        reserve_floor_bps: 787,
        rollover_grace: 2,
        max_notes: 83,
        withdrawal_delay: 3,
        audit_weight: 37,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW308",
        reserve_floor_bps: 788,
        rollover_grace: 3,
        max_notes: 84,
        withdrawal_delay: 4,
        audit_weight: 38,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW309",
        reserve_floor_bps: 789,
        rollover_grace: 4,
        max_notes: 85,
        withdrawal_delay: 5,
        audit_weight: 39,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
    WindowProfile {
        code: "NW310",
        reserve_floor_bps: 790,
        rollover_grace: 5,
        max_notes: 86,
        withdrawal_delay: 1,
        audit_weight: 40,
        settlement_label: "nightfall-retail",
        recommended_batch: BatchClass::Micro,
    },
    WindowProfile {
        code: "NW311",
        reserve_floor_bps: 791,
        rollover_grace: 6,
        max_notes: 87,
        withdrawal_delay: 2,
        audit_weight: 41,
        settlement_label: "twilight-corporate",
        recommended_batch: BatchClass::Small,
    },
    WindowProfile {
        code: "NW312",
        reserve_floor_bps: 792,
        rollover_grace: 1,
        max_notes: 88,
        withdrawal_delay: 3,
        audit_weight: 42,
        settlement_label: "lunar-archive",
        recommended_batch: BatchClass::Medium,
    },
    WindowProfile {
        code: "NW313",
        reserve_floor_bps: 793,
        rollover_grace: 2,
        max_notes: 89,
        withdrawal_delay: 4,
        audit_weight: 43,
        settlement_label: "eclipse-route",
        recommended_batch: BatchClass::Institutional,
    },
    WindowProfile {
        code: "NW314",
        reserve_floor_bps: 794,
        rollover_grace: 3,
        max_notes: 90,
        withdrawal_delay: 5,
        audit_weight: 44,
        settlement_label: "midnight-vault",
        recommended_batch: BatchClass::Settlement,
    },
];

pub fn profile_by_code(code: &str) -> Option<&'static WindowProfile> {
    WINDOW_PROFILES.iter().find(|profile| profile.code == code)
}

pub fn profiles_for_batch(class: BatchClass) -> Vec<&'static WindowProfile> {
    WINDOW_PROFILES
        .iter()
        .filter(|profile| profile.recommended_batch == class)
        .collect()
}

pub fn weighted_rollover_budget(class: BatchClass) -> u64 {
    profiles_for_batch(class)
        .into_iter()
        .map(|profile| profile.rollover_grace * u64::from(profile.audit_weight))
        .sum()
}

pub fn conservative_profile(note_count: usize) -> &'static WindowProfile {
    WINDOW_PROFILES
        .iter()
        .find(|profile| profile.accepts_note_count(note_count))
        .unwrap_or(&DEFAULT_PROFILE)
}
